### ISSUE TITLE
Image Collecting [question]

### ISSUE THREAD

**Issue by Ltooo4** [captcha-challenger/hcaptcha-model-factory#44]
**Question**
Tried using this but i dont have enough images to work with. How will i get 1000+ images??

**Comment by QIN2DIM** [comment]
You need to iterate a few versions, and generally the positive and negative examples add up to about 500 and the effect is good.

**Comment by QIN2DIM** [comment]
You don't need too many pictures at the beginning

**Comment by Ltooo4** [comment]
> You need to iterate a few versions, and generally the positive and negative examples add up to about 500 and the effect is good.

Where do i get the pictures from my dumb ass cant even get 50 💀
