### ISSUE TITLE
unable to install dependencies.

### ISSUE THREAD

**Issue by diegoooooooooooooooo** [captcha-challenger/hcaptcha-model-factory#45]
With which version of python should I install the dependencies?

do you plan to update?

Because for the moment impossible to train a model

![image](https://user-images.githubusercontent.com/38768160/208642856-8b731f20-dead-4fea-81d1-06fc9ea95ef7.png)
![image](https://user-images.githubusercontent.com/38768160/208642521-39581693-f461-4b3c-bbc1-de8e1fdc04dd.png)

**Comment by diegoooooooooooooooo** [comment]
I managed to install everything, thank you on the other hand I always have this error when I try to train a model however, I did everything correctly, as well as put the images in the unlabel folder

How to solve this problem

![image](https://user-images.githubusercontent.com/38768160/209024020-105123b6-e5d8-433e-afa8-0f6d2092637c.png)

**Comment by QIN2DIM** [comment]
What's your command

**Comment by QIN2DIM** [comment]
[hedgehog_on_rocks.zip](https://github.com/captcha-challenger/hcaptcha-model-factory/files/10283330/hedgehog_on_rocks.zip)

**Comment by diegoooooooooooooooo** [comment]
> 
Basically, it's during training
my command is python main.py new
![image](https://user-images.githubusercontent.com/38768160/209050581-d9c1edbe-adff-4589-adaa-4e702a73e64f.png)

**Comment by QIN2DIM** [comment]
Trainval

**Comment by diegoooooooooooooooo** [comment]
![image](https://user-images.githubusercontent.com/38768160/209123252-b54410b3-4d12-40f8-8bff-127e13e08953.png)

**Comment by beiyuouo** [comment]
Please check whether your data is in the correct path.
